name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Arduino Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          path: .
          compliance: strict

  setup-arduino-cli:
    name: Setup Arduino CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: latest

      - name: Install Adafruit nRF52 Board Package
        run: |
          arduino-cli core update-index
          arduino-cli core install adafruit:nrf52

      - name: Install Required Libraries
        run: |
          arduino-cli lib install "Adafruit APDS9960"
          arduino-cli lib install "Adafruit BMP280 Library"
          arduino-cli lib install "Adafruit LIS3MDL"
          arduino-cli lib install "Adafruit LSM6DS33"
          arduino-cli lib install "Adafruit LSM6DS3TR-C"
          arduino-cli lib install "Adafruit SHT31 Library"
          arduino-cli lib install "Adafruit Unified Sensor"
          arduino-cli lib install "PDM"
          arduino-cli lib install "Adafruit Bluefruit nRF52 Libraries"

  compile:
    name: Compile Arduino Sketches
    needs: setup-arduino-cli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: latest

      - name: Compile All Sketches
        uses: arduino/test-compile-for-arduino@v1
        with:
          fqbn: adafruit:nrf52:feather52840sense
          sketch-path: sketches
